### PR TITLE
bump purescript-enums version to 0.3.0.

### PR DESCRIPTION
**Pull request by philopon**
Hi!

I bumped version of purescript-enums to 0.3.0.

Regards.

### CODE REVIEW

**Comment by jdegoes** [comment]
You can simplify the `pred` / `succ` methods with these additions (reduce them to 1 liners).

**Comment by philopon** [comment]
Thanks for your comment!

I use naive implementation, because I'm afraid of bottleneck of default*. Do you think about it?

And, Should I rewrite pred/succ using defaultPred/Succ methods instead of toEnum/fromEnum using defaultToEnum/FromEnum?
It seems to reduce diff to use defaultToEnum/FromEnum.

**Comment by jdegoes** [comment]
You can write `pred` / `succ` in terms of `toEnum` / `fromEnum`.

**Comment by philopon** [comment]
I wrote. please check it!

**Comment by jdegoes** [comment]
:shipit: 

Note I don't have permissions for this repo but @garyb can help get this merged.

**Comment by garyb** [comment]
Thanks!

**Comment by philopon** [comment]
Thanks for your code review and merge:smile:

**Pull request merged**
